# Generated by Django 5.1.2 on 2024-11-24 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_wellnesstransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('permanent', 'Permanent')], default='on_hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('admitted', 'Admitted')], default='on_hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnesstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wellnesstransaction',
            name='category',
            field=models.CharField(choices=[('diet', 'Diet'), ('fitness', 'Fitness'), ('medical', 'Medical'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sleep_hours', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('steps', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('calories_burned', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hydration', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('activity_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
